#!/usr/bin/env bash
# configure a load balancer to serve two servers

# Update and install necessary packages
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option  redispatch
    maxconn 2000
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats

    acl is_web01 hdr(host) -i 393968-web-01
    acl is_web02 hdr(host) -i 393968-web-02

    use_backend web01_backend if is_web01
    use_backend web02_backend if is_web02

backend web01_backend
    balance roundrobin
    server web-01 54.144.146.250:80 check

backend web02_backend
    balance roundrobin
    server web-02 34.227.89.63:80 check
EOF

# Enable and start HAProxy service
sudo systemctl enable haproxy
sudo systemctl restart haproxy
