#!/bin/env bash
# Use the ps command to list all processes and format the output

# to include user, PID, %CPU, %MEM, VSZ, RSS, TTY, STAT, START, TIME, and COMMAND.
ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest
